- name: Deploy Dockerized Nginx app on Azure Ubuntu VM
  hosts: web
  become: true
  vars:
    app_src: ../../app/
    app_dest: /home/azureuser/app
    docker_image: klyra-nginx
    container_name: klyra-nginx

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add azureuser to docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Copy app to server
      copy:
        src: "{{ app_src }}"
        dest: "{{ app_dest }}"
        owner: azureuser
        group: azureuser
        mode: 0755

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: build
        build:
          path: "{{ app_dest }}"
          nocache: yes


    - name: Ensure Docker container is stopped and removed if exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: Ensure Docker container is running
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"

