- name: Deploy Dockerized Nginx app
  hosts: web
  become: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - git
        state: present

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Copy app to server
      copy:
        src: ../../app/
        dest: /home/ec2-user/app
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Build Docker image
      command: docker build -t klyra-nginx /home/ec2-user/app
      args:
        chdir: /home/ec2-user/app

    - name: Run Docker container
      command: docker run -d -p 80:80 --name klyra-nginx klyra-nginx
      ignore_errors: yes
