name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add EC2 SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/klyra-nginx-key.pem
          chmod 600 ~/.ssh/klyra-nginx-key.pem

      - name: Install Ansible on runner
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.ini ansible/playbooks/deploy.yml \
            --private-key ~/.ssh/klyra-nginx-key.pem -u ec2-user

      - name: Test container is running
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/klyra-nginx-key.pem ec2-user@$(cat ansible/
