name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Add EC2 private key from GitHub Secrets
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/klyra-nginx-key.pem
          chmod 600 ~/.ssh/klyra-nginx-key.pem
          # Disable strict host key checking to avoid prompt
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # Step 3: Run Ansible playbook on EC2
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.ini \
          ansible/playbooks/deploy.yml \
          --private-key ~/.ssh/klyra-nginx-key.pem -u ec2-user
