name: Deploy Nginx App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python for Ansible
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install Ansible and Docker client
      - name: Install Ansible and Docker client
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible docker.io

      # 4. Add SSH key from GitHub secrets
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/klyra-nginx-key.pem
          chmod 600 ~/.ssh/klyra-nginx-key.pem
          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # 5. Run the Ansible playbook
      - name: Deploy via Ansible
        run: |
          ansible-playbook -i ansible/inventory/aws_ec2.ini ansible/playbooks/deploy.yml \
            --private-key ~/.ssh/klyra-nginx-key.pem -u ec2-user
